---
# ConfigMap for certification-gcp cluster
# Contains Conductor connection details specific to this cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-sdk-harness-config
  # namespace: xxxxx # supply this in kubectl command
  labels:
    app: rust-sdk-harness-worker
data:
  CONDUCTOR_SERVER_URL: "https://certification-gcp.orkesconductor.com/api"
  CONDUCTOR_AUTH_KEY: "e6c1ac61-286b-11f1-be01-c682b5750c3a"
