---
# ConfigMap for certification-aws cluster
# Contains Conductor connection details specific to this cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-sdk-harness-config
  # namespace: xxxxx # supply this in kubectl command
  labels:
    app: rust-sdk-harness-worker
data:
  CONDUCTOR_SERVER_URL: "https://certification-aws.orkesconductor.io/api"
  CONDUCTOR_AUTH_KEY: "7ba9d0ec-247b-11f1-8d42-ea3efeda41b2"
