//! # Conductor Rust SDK
//!
//! Rust SDK for working with [Netflix Conductor](https://github.com/conductor-oss/conductor)
//! workflow orchestration platform.
//!
//! ## Quick Start
//!
//! ### Using FnWorker (recommended for most cases)
//!
//! ```rust,no_run
//! use conductor::{Configuration, TaskHandler, Task};
//! use conductor::worker::{FnWorker, WorkerOutput};
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let config = Configuration::default();
//!
//!     // Create a worker using FnWorker
//!     let greet_worker = FnWorker::new("greet", |task: Task| async move {
//!         let name = task.get_input_string("name").unwrap_or_default();
//!         Ok(WorkerOutput::completed_with_result(format!("Hello, {}!", name)))
//!     })
//!     .with_thread_count(5);
//!
//!     // Create and start task handler
//!     let mut handler = TaskHandler::new(config)?;
//!     handler.add_worker(greet_worker);
//!     handler.start().await?;
//!
//!     // Keep running...
//!     tokio::signal::ctrl_c().await?;
//!     handler.stop().await?;
//!
//!     Ok(())
//! }
//! ```
//!
//! ### Using #[worker] macro (requires "macros" feature)
//!
//! ```rust,ignore
//! use conductor::{Configuration, TaskHandler};
//! use conductor_macros::worker;
//!
//! // Define a worker using the macro - similar to Python's @worker_task
//! #[worker(name = "greet", thread_count = 5)]
//! async fn greet(name: String) -> String {
//!     format!("Hello, {}!", name)
//! }
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let config = Configuration::default();
//!
//!     let mut handler = TaskHandler::new(config)?;
//!     handler.add_worker(greet_worker()); // Generated by macro
//!     handler.start().await?;
//!
//!     tokio::signal::ctrl_c().await?;
//!     handler.stop().await?;
//!     Ok(())
//! }
//! ```
//!
//! ## Features
//!
//! - **Async Workers**: Native async/await support with Tokio runtime
//! - **Batch Polling**: Dynamic batch size based on worker capacity
//! - **Adaptive Backoff**: Exponential backoff when queue is empty
//! - **Hierarchical Config**: Environment-based configuration override
//! - **Prometheus Metrics**: Built-in metrics collection
//! - **Event-Driven**: Extensible event system for custom monitoring
//! - **JSON Schema**: Automatic schema generation from Rust types
//! - **Procedural Macros**: Optional `#[worker]` attribute macro (enable "macros" feature)

pub mod client;
pub mod configuration;
pub mod error;
pub mod events;
pub mod http;
pub mod metrics;
pub mod models;
pub mod schema;
pub mod worker;

// Re-exports for convenience
pub use client::{
    AuthorizationClient, ConductorClient, EventClient, IntegrationClient, MetadataClient,
    OrkesClients, PromptClient, QueueConfiguration, SchedulerClient, SchemaClient, SecretClient,
    TaskClient, WorkflowClient,
};
pub use configuration::{Configuration, WorkerConfig};
pub use error::{ConductorError, Result};
pub use events::{EventDispatcher, TaskRunnerEvent, TaskRunnerEventsListener};
pub use metrics::{MetricsCollector, MetricsSettings};
pub use models::{
    AccessKey, AccessType, ChatMessage, ConductorApplication, ConductorUser,
    CreateOrUpdateApplicationRequest, CreatedAccessKey, EmbeddedTaskDef, GrantedPermission, Group,
    Integration, IntegrationApi, IntegrationApiUpdate, IntegrationUpdate, MetadataTag, Permission,
    PromptTemplate, Role, SaveScheduleRequest, SchemaDef, SearchResultWorkflowScheduleExecution,
    StartWorkflowRequest, StartWorkflowScheduleRequest, StateChangeConfig, StateChangeEvent,
    StateChangeEventType, SubWorkflowParams, SubjectRef, SubjectType, TargetRef, TargetType, Task,
    TaskDef, TaskInProgress, TaskResult, TaskResultStatus, TaskStatus, TaskType,
    UpsertGroupRequest, UpsertUserRequest, Workflow, WorkflowDef, WorkflowSchedule,
    WorkflowScheduleExecution, WorkflowStatus, WorkflowTask, WorkflowTimeoutPolicy,
};
pub use worker::{
    FnWorker, TaskContext, TaskHandler, TaskRunner, Worker, WorkerHost, WorkerOutput,
};

// Re-export the procedural macros when the feature is enabled
#[cfg(feature = "macros")]
pub use conductor_macros::{worker, worker_task};
